version: '3.1'

services:
  mongo:
    image: mongo:3-jessie
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-password
    secrets:
      - mongo-password

secrets:
  mongo-password:
    file: ./mongo-password

volumes:
  mongodata:
